export enum EntryType {
   NATIONAL_CODE_ENTRY = 'NATIONAL_CODE_ENTRY',
   CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER',
   INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
   ORGANIZATION_CODE_ENTRY = "ORGANIZATION_CODE_ENTRY"
}
