stages:
  - build
  - run
.build:
  script:
    - hostname
    - echo "${ENVS}" > .env
    - docker compose build;

.run:
  script:
    - hostname
    - docker compose up -d;
    - sleep 4;

Pre-Prod-build:
  extends:
    - .build
  stage: build
  variables:
    ENVS: ${PP_ENV}
  only:
    - pre-production
    - test-pipeline
  tags:
    - pre-prod

Pre-Prod-run:
  extends:
    - .run
  stage: run
  only:
    - pre-production
    - test-pipeline
  tags:
    - pre-prod

test-build:
  extends:
    - .build
  stage: build
  variables:
    ENVS: ${TEST_ENV}
  only:
    - test

test-run:
  extends:
    - .run
  stage: run
  only:
    - test
