stages:
  - build
  - run
build-front-prod:
  stage: build
  only:
    - stage
  script:
    - hostname
    - docker compose build;
  tags: [stage]

run-front-prod:
  stage: run
  only:
    - stage
  script:
    - hostname
    - docker compose up -d;
  tags: [stage]

