---
services:
  front:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
      args:
        EXTRA_HOST: "nexus.zaraamad.ir:192.168.174.4"
    container_name: zarvand-fe-project
    restart: always
    ports:
      - 80:80
    networks:
      - ProjectNet
    extra_hosts:
      - "nexus.zaraamad.ir:192.168.174.4"
    env_file:
      - ../.env

networks:
  ProjectNet:
    name: test
    external: true
