FROM node:21-alpine as builder

WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

ARG VITE_APP_BACKEND
ENV VITE_APP_BACKEND=$VITE_APP_BACKEND

RUN npm run build

# CMD [ "yarn", "start" ]

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
